ALTER table stockmoves CHANGE reference reference varchar(100) NOT NULL DEFAULT '';
alter table stockcatproperties drop foreign key stockcatproperties_ibfk_2;
alter table stockcatproperties drop foreign key stockcatproperties_ibfk_3;
ALTER TABLE  `emailsettings` CHANGE  `username`  `username` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
CREATE TABLE IF NOT EXISTS `pricematrix` (
  `salestype` char(2) NOT NULL DEFAULT '',
  `stockid` varchar(20) NOT NULL DEFAULT '',
  `quantitybreak` int(11) NOT NULL DEFAULT '1',
  `price` double NOT NULL DEFAULT '0',
  PRIMARY KEY (`salestype`,`stockid`,`quantitybreak`),
  KEY `DiscountCategory` (`stockid`),
  KEY `SalesType` (`salestype`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO scripts VALUES('PriceMatrix.php',11,'Mantain stock prices according to quantity break and sales types');
DELETE FROM scripts WHERE script='FixedAssetList.php';
DELETE FROM scripts WHERE script='ManualContents.php';
DELETE FROM scripts WHERE script='MenuAccess.php';
DELETE FROM scripts WHERE script='OrderEntryDiscountPricing.php';
DELETE FROM scripts WHERE script='PrintSalesOrder.php';
DELETE FROM scripts WHERE script='ReportBug.php';
DELETE FROM scripts WHERE script='ReportletContainer.php';
DELETE FROM scripts WHERE script='SystemCheck.php';
UPDATE holdreasons set dissallowinvoices=2 WHERE reasoncode=20;
ALTER table stockmoves CHANGE reference reference varchar(100) NOT NULL DEFAULT '';
ALTER TABLE bom ADD COLUMN sequence INT(11) NOT NULL DEFAULT 0 AFTER parent;
INSERT INTO scripts VALUES('TopCustomers.php',1,'Shows the top customers');
ALTER TABLE accountgroups ENGINE=INNODB;
ALTER TABLE accountsection ENGINE=INNODB;
ALTER TABLE areas ENGINE=INNODB;
ALTER TABLE assetmanager ENGINE=INNODB;
ALTER TABLE audittrail ENGINE=INNODB;
ALTER TABLE bankaccounts ENGINE=INNODB;
ALTER TABLE bankaccountusers ENGINE=INNODB;
ALTER TABLE banktrans ENGINE=INNODB;
ALTER TABLE bom ENGINE=INNODB;
ALTER TABLE chartdetails ENGINE=INNODB;
ALTER TABLE chartmaster ENGINE=INNODB;
ALTER TABLE cogsglpostings ENGINE=INNODB;
ALTER TABLE companies ENGINE=INNODB;
ALTER TABLE config ENGINE=INNODB;
ALTER TABLE contractbom ENGINE=INNODB;
ALTER TABLE contractcharges ENGINE=INNODB;
ALTER TABLE contractreqts ENGINE=INNODB;
ALTER TABLE contracts ENGINE=INNODB;
ALTER TABLE currencies ENGINE=INNODB;
ALTER TABLE custallocns ENGINE=INNODB;
ALTER TABLE custbranch ENGINE=INNODB;
ALTER TABLE custcontacts ENGINE=INNODB;
ALTER TABLE custnotes ENGINE=INNODB;
ALTER TABLE debtorsmaster ENGINE=INNODB;
ALTER TABLE debtortrans ENGINE=INNODB;
ALTER TABLE debtortranstaxes ENGINE=INNODB;
ALTER TABLE debtortype ENGINE=INNODB;
ALTER TABLE debtortypenotes ENGINE=INNODB;
ALTER TABLE deliverynotes ENGINE=INNODB;
ALTER TABLE departments ENGINE=INNODB;
ALTER TABLE discountmatrix ENGINE=INNODB;
ALTER TABLE ediitemmapping ENGINE=INNODB;
ALTER TABLE edimessageformat ENGINE=INNODB;
ALTER TABLE edi_orders_segs ENGINE=INNODB;
ALTER TABLE edi_orders_seg_groups ENGINE=INNODB;
ALTER TABLE emailsettings ENGINE=INNODB;
ALTER TABLE factorcompanies ENGINE=INNODB;
ALTER TABLE fixedassetcategories ENGINE=INNODB;
ALTER TABLE fixedassetlocations ENGINE=INNODB;
ALTER TABLE fixedassetmoves ENGINE=INNODB;
ALTER TABLE fixedassets ENGINE=INNODB;
ALTER TABLE fixedassettasks ENGINE=INNODB;
ALTER TABLE fixedassettrans ENGINE=INNODB;
ALTER TABLE freightcosts ENGINE=INNODB;
ALTER TABLE geocode_param ENGINE=INNODB;
ALTER TABLE gltrans ENGINE=INNODB;
ALTER TABLE grns ENGINE=INNODB;
ALTER TABLE holdreasons ENGINE=INNODB;
ALTER TABLE internalstockcatrole ENGINE=INNODB;
ALTER TABLE labelfields ENGINE=INNODB;
ALTER TABLE labels ENGINE=INNODB;
ALTER TABLE lastcostrollup ENGINE=INNODB;
ALTER TABLE levels ENGINE=INNODB;
ALTER TABLE locations ENGINE=INNODB;
ALTER TABLE locstock ENGINE=INNODB;
ALTER TABLE loctransfers ENGINE=INNODB;
ALTER TABLE mailgroupdetails ENGINE=INNODB;
ALTER TABLE mailgroups ENGINE=INNODB;
ALTER TABLE manufacturers ENGINE=INNODB;
ALTER TABLE mrpcalendar ENGINE=INNODB;
ALTER TABLE mrpdemands ENGINE=INNODB;
ALTER TABLE mrpdemandtypes ENGINE=INNODB;
ALTER TABLE mrpparameters ENGINE=INNODB;
ALTER TABLE mrpplannedorders ENGINE=INNODB;
ALTER TABLE mrprequirements ENGINE=INNODB;
ALTER TABLE mrpsupplies ENGINE=INNODB;
ALTER TABLE offers ENGINE=INNODB;
ALTER TABLE orderdeliverydifferenceslog ENGINE=INNODB;
ALTER TABLE paymentmethods ENGINE=INNODB;
ALTER TABLE paymentterms ENGINE=INNODB;
ALTER TABLE pcashdetails ENGINE=INNODB;
ALTER TABLE pcexpenses ENGINE=INNODB;
ALTER TABLE pctabexpenses ENGINE=INNODB;
ALTER TABLE pctabs ENGINE=INNODB;
ALTER TABLE pctypetabs ENGINE=INNODB;
ALTER TABLE periods ENGINE=INNODB;
ALTER TABLE pickinglistdetails ENGINE=INNODB;
ALTER TABLE pickinglists ENGINE=INNODB;
ALTER TABLE prices ENGINE=INNODB;
ALTER TABLE purchdata ENGINE=INNODB;
ALTER TABLE purchorderauth ENGINE=INNODB;
ALTER TABLE purchorderdetails ENGINE=INNODB;
ALTER TABLE purchorders ENGINE=INNODB;
ALTER TABLE recurringsalesorders ENGINE=INNODB;
ALTER TABLE recurrsalesorderdetails ENGINE=INNODB;
ALTER TABLE reportcolumns ENGINE=INNODB;
ALTER TABLE reportheaders ENGINE=INNODB;
ALTER TABLE reportlinks ENGINE=INNODB;
ALTER TABLE salesanalysis ENGINE=INNODB;
ALTER TABLE salescat ENGINE=INNODB;
ALTER TABLE salescatprod ENGINE=INNODB;
ALTER TABLE salescattranslations ENGINE=INNODB;
ALTER TABLE salesglpostings ENGINE=INNODB;
ALTER TABLE salesman ENGINE=INNODB;
ALTER TABLE salesorderdetails ENGINE=INNODB;
ALTER TABLE salesorders ENGINE=INNODB;
ALTER TABLE salestypes ENGINE=INNODB;
ALTER TABLE scripts ENGINE=INNODB;
ALTER TABLE securitygroups ENGINE=INNODB;
ALTER TABLE securityroles ENGINE=INNODB;
ALTER TABLE securitytokens ENGINE=INNODB;
ALTER TABLE sellthroughsupport ENGINE=INNODB;
ALTER TABLE shipmentcharges ENGINE=INNODB;
ALTER TABLE shipments ENGINE=INNODB;
ALTER TABLE shippers ENGINE=INNODB;
ALTER TABLE stockcategory ENGINE=INNODB;
ALTER TABLE stockcatproperties ENGINE=INNODB;
ALTER TABLE stockcheckfreeze ENGINE=INNODB;
ALTER TABLE stockcounts ENGINE=INNODB;
ALTER TABLE stockdescriptiontranslations ENGINE=INNODB;
ALTER TABLE stockitemproperties ENGINE=INNODB;
ALTER TABLE stockmaster ENGINE=INNODB;
ALTER TABLE stockmoves ENGINE=INNODB;
ALTER TABLE stockmovestaxes ENGINE=INNODB;
ALTER TABLE stockrequest ENGINE=INNODB;
ALTER TABLE stockrequestitems ENGINE=INNODB;
ALTER TABLE stockserialitems ENGINE=INNODB;
ALTER TABLE stockserialmoves ENGINE=INNODB;
ALTER TABLE suppallocs ENGINE=INNODB;
ALTER TABLE suppliercontacts ENGINE=INNODB;
ALTER TABLE supplierdiscounts ENGINE=INNODB;
ALTER TABLE suppliers ENGINE=INNODB;
ALTER TABLE suppliertype ENGINE=INNODB;
ALTER TABLE supptrans ENGINE=INNODB;
ALTER TABLE supptranstaxes ENGINE=INNODB;
ALTER TABLE systypes ENGINE=INNODB;
ALTER TABLE tags ENGINE=INNODB;
ALTER TABLE taxauthorities ENGINE=INNODB;
ALTER TABLE taxauthrates ENGINE=INNODB;
ALTER TABLE taxcategories ENGINE=INNODB;
ALTER TABLE taxgroups ENGINE=INNODB;
ALTER TABLE taxgrouptaxes ENGINE=INNODB;
ALTER TABLE taxprovinces ENGINE=INNODB;
ALTER TABLE tenderitems ENGINE=INNODB;
ALTER TABLE tenders ENGINE=INNODB;
ALTER TABLE tendersuppliers ENGINE=INNODB;
ALTER TABLE transby ENGINE=INNODB;
ALTER TABLE unitsofmeasure ENGINE=INNODB;
ALTER TABLE woitems ENGINE=INNODB;
ALTER TABLE worequirements ENGINE=INNODB;
ALTER TABLE workcentres ENGINE=INNODB;
ALTER TABLE workorders ENGINE=INNODB;
ALTER TABLE woserialnos ENGINE=INNODB;
ALTER TABLE www_users ENGINE=INNODB;
INSERT INTO `scripts` (`script`, `pagesecurity`, `description`) VALUES 
('Getstocknamepinyin.php', '2', '汉字转拼音'),
('CNCERP_GLShows.php', '2', '弹窗凭证显示');
UPDATE `www_users` SET `theme` = 'stisla';
UPDATE config SET confvalue='4.11.3' WHERE confname='VersionNumber';
